# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b96df238579ef022d25890b157347afd0dadb2b7e83782580ff74ee98e05c672d15a6ad179c9625de8a857333d97115215f7357dbc9a7c322aa17352a2779f5d

test:
  secret_key_base: 830d92feec0c9d2eeceba21ef514161d84e340db5fe8e55f110b69a9dd9356ecfee01a403173aebc25ae76c8cc2d2d50561e7031909eab8267fa1b45fc81540d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
